name: TERRAFORM DESTROY

on:
  workflow_dispatch:   # ✅ manual trigger only

jobs:
  destroy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    # ✅ Configure AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # ✅ Terraform Init
    - name: Terraform Init
      run: |
        cd devops
        terraform init

    # ✅ Terraform Destroy
    - name: Terraform Destroy
      run: |
        cd devops
        terraform destroy -var="tag=${{ env.v.0.8 }}" -auto-approve-auto-approve
